### PR TITLE
Add user, workdir config

### PR DESCRIPTION
**Pull request by archmagece**
# Context

Can I PR this addition?

Setting 'user' permissions and 'workdir' when using commands

```yaml
/dip.yml
  bash:
    description: Open the Bash - root user
    workdir: /home/jjj
    # user: root:root
    user: "33:33"
    # user: 33:33 # this not working
    service: app
    command: /bin/bash
```

```json
/schema.json
        "workdir": {
          "type": "string",
          "description": "Specifies the working directory for the command",
          "examples": ["/workdir", "/app"]
        },
        "user": {
          "type": "string",
          "description": "Specifies the user to run the command as",
          "examples": ["root:root", "root", "www-data", "1000:1000"]
        },
```

### CODE REVIEW

**Comment by bibendi** [comment]
Hey! You can configure `working_dir` and `user` in a docker-compose.yml. Please check the dip readme. Why is this approach not suitable for your needs?

**Comment by archmagece** [comment]
Thank you for your fast response.

In my case, situation where I need this.

ex) Run the server as 'root' and the rails command as 'discourse'.

```yaml
# docker-compose.yml
services:
  rails:
    user: root
    workdir: /
...
```

```yaml
instruction:
  rails:
    description: Rails commands
    service: rails
    command: bundle exec rails
    workdir: /src
    user: discourse:discourse
```

**Comment by bibendi** [comment]
It seems something wrong in your app architecture.
Anyway, you can do like the following:

```yaml
# docker-compose.yml
services:
  rails:
    user: ${RAILS_USER:-root}
    working_dir: ${RAILS_DIR:-/}

# dip.yml
interaction:
  rails:
    environment:
      RAILS_USER: discourse:discourse
      RAILS_DIR: /src
    description: Rails commands
    service: rails
    command: bundle exec rails
```

**Comment by archmagece** [comment]
Thank you.

I think it's because this is a unique use case, so I'm going to modify the source to use it at this time.

**Pull request closed without merging**
